package com.sherpaonnx.alignment.core

object AlignmentErrorCodes {
  const val TAG = "SherpaOnnxAlignment"

  const val ERR_ALIGNMENT = "ALIGNMENT_ERROR"
  const val ERR_CONSTRAINED_ACCURATE = "ALIGNMENT_CONSTRAINED_ACCURATE_ERROR"
  const val ERR_TEXT_NOT_FOUND = "ALIGNMENT_TEXT_BUFFER_NOT_FOUND"
  const val ERR_TEXT_KIND_MISMATCH = "ALIGNMENT_TEXT_BUFFER_KIND_MISMATCH"
  const val ERR_TEXT_EMPTY = "ALIGNMENT_TEXT_BUFFER_EMPTY"
  const val ERR_AUDIO_NOT_FOUND = "ALIGNMENT_AUDIO_BUFFER_NOT_FOUND"
  const val ERR_AUDIO_KIND_MISMATCH = "ALIGNMENT_AUDIO_BUFFER_KIND_MISMATCH"
  const val ERR_AUDIO_EMPTY = "ALIGNMENT_AUDIO_BUFFER_EMPTY"
  const val ERR_MODEL_LOAD_FAILED = "ALIGNMENT_MODEL_LOAD_FAILED"
  const val ERR_NATIVE_ACCURATE_FAILED = "ALIGNMENT_NATIVE_ACCURATE_FAILED"
  const val ERR_FORCED_CTC_FAILED = "ALIGNMENT_FORCED_CTC_FAILED"
  const val ERR_ANCHOR_OUT_OF_RANGE = "ALIGNMENT_ANCHOR_OUT_OF_RANGE"
  const val ERR_NATIVE_UNKNOWN = "ALIGNMENT_NATIVE_UNKNOWN"
  const val OFFLINE_OOM = "OFFLINE_OOM"
}
