default_platform(:android)

platform :android do
  desc "Upload AAB to Play Store closed testing"
  lane :closed_testing do
    supply(
      aab: "app/build/outputs/bundle/release/app-release.aab",
      track: "closed_testing",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
