import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F7FB',
  },
  body: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 36,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E4E6EB',
  },
  sectionHeader: {
    marginBottom: 14,
  },
  stepBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#E9F2FF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 10,
  },
  stepBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1565C0',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#16181D',
    marginBottom: 8,
  },
  sectionDescription: {
    fontSize: 14,
    color: '#667085',
    lineHeight: 21,
  },
  modeGrid: {
    gap: 10,
  },
  modeCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D7DAE0',
    backgroundColor: '#FBFCFE',
    padding: 14,
  },
  modeCardActive: {
    borderColor: '#007AFF',
    backgroundColor: '#EAF4FF',
  },
  modeCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1C1C1E',
    marginBottom: 6,
  },
  modeCardTitleActive: {
    color: '#0059D6',
  },
  modeCardDescription: {
    fontSize: 13,
    color: '#5C6270',
    lineHeight: 19,
  },
  modeMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  metaPill: {
    borderRadius: 999,
    backgroundColor: '#F0F2F5',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  metaPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475467',
  },
  currentModelContainer: {
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#EAF4FF',
  },
  currentModelText: {
    fontSize: 14,
    color: '#1565C0',
    fontWeight: '700',
  },
  currentModelMetaText: {
    marginTop: 4,
    fontSize: 12,
    color: '#1E88E5',
    lineHeight: 18,
  },
  inputLabel: {
    fontSize: 14,
    color: '#16181D',
    fontWeight: '600',
    marginBottom: 8,
    marginTop: 4,
  },
  textInput: {
    backgroundColor: '#F5F7FA',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#111827',
    fontSize: 15,
    minHeight: 108,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#E4E7EC',
  },
  inlineInput: {
    backgroundColor: '#F5F7FA',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#111827',
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#E4E7EC',
  },
  inlineHelpText: {
    marginTop: 8,
    fontSize: 12,
    color: '#667085',
    lineHeight: 18,
  },
  hintCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFF8E1',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFD54F',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  hintText: {
    flex: 1,
    fontSize: 13,
    color: '#795548',
    lineHeight: 18,
  },
  button: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  applyButton: {
    marginTop: 12,
  },
  generateButton: {
    marginTop: 14,
  },
  selectedFileCard: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F9FAFB',
  },
  selectedFileLabel: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 4,
  },
  selectedFileName: {
    fontSize: 15,
    color: '#111827',
    fontWeight: '600',
  },
  selectedFileMeta: {
    marginTop: 4,
    fontSize: 12,
    color: '#667085',
  },
  choiceList: {
    gap: 10,
  },
  choiceCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D7DAE0',
    backgroundColor: '#FBFCFE',
    padding: 12,
  },
  choiceCardActive: {
    borderColor: '#007AFF',
    backgroundColor: '#EAF4FF',
  },
  choiceCardDisabled: {
    opacity: 0.5,
  },
  choiceTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1C1C1E',
    marginBottom: 4,
  },
  choiceTitleActive: {
    color: '#0059D6',
  },
  choiceTitleDisabled: {
    color: '#7A8190',
  },
  choiceDescription: {
    fontSize: 13,
    color: '#5C6270',
    lineHeight: 18,
  },
  choiceReason: {
    marginTop: 8,
    fontSize: 12,
    color: '#9A3412',
    lineHeight: 17,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    color: '#6D6D72',
  },
  warningContainer: {
    marginTop: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFD54F',
    backgroundColor: '#FFF8E1',
    padding: 12,
  },
  warningBannerText: {
    fontSize: 13,
    color: '#795548',
    lineHeight: 18,
  },
  warningList: {
    marginTop: 6,
    gap: 4,
  },
  warningListItem: {
    fontSize: 13,
    color: '#795548',
    lineHeight: 18,
  },
  readyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    backgroundColor: '#E8F5E9',
    borderWidth: 1,
    borderColor: '#A5D6A7',
    padding: 12,
  },
  readyText: {
    flex: 1,
    fontSize: 13,
    color: '#1B5E20',
    fontWeight: '600',
  },
  modelButtons: {
    gap: 10,
  },
  modelSelectButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D1D6',
    backgroundColor: '#F9F9FB',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  modelSelectButtonActive: {
    borderColor: '#007AFF',
    backgroundColor: '#EAF4FF',
  },
  modelSelectButtonInitialized: {
    borderColor: '#34C759',
  },
  modelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
  },
  modelSelectButtonTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#1C1C1E',
  },
  modelSelectButtonTitleActive: {
    color: '#0059D6',
  },
  modelSelectButtonId: {
    fontSize: 12,
    color: '#6D6D72',
  },
  recommendedBadge: {
    borderRadius: 999,
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  recommendedBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#2E7D32',
    textTransform: 'uppercase',
  },
  resultCard: {
    backgroundColor: '#F5F7FA',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E4E7EC',
  },
  resultMetaText: {
    fontSize: 14,
    color: '#1C1C1E',
    fontWeight: '700',
    marginBottom: 6,
  },
  resultAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  resultCodeText: {
    fontSize: 12,
    color: '#475467',
    marginBottom: 3,
    lineHeight: 18,
  },
  subtitleList: {
    gap: 8,
  },
  subtitleItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  subtitleText: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '600',
    marginBottom: 4,
  },
  subtitleTime: {
    fontSize: 12,
    color: '#667085',
    lineHeight: 18,
  },
  emptyText: {
    fontSize: 14,
    color: '#8E8E93',
    lineHeight: 20,
  },
  errorContainer: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: '#FFEBEE',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#F5C2C7',
  },
  errorTitle: {
    color: '#B42318',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  errorCode: {
    color: '#B42318',
    fontSize: 12,
    marginBottom: 4,
  },
  errorText: {
    color: '#B42318',
    fontSize: 14,
    lineHeight: 20,
  },
});
