package com.sherpaonnx.separation.core

internal object SeparationErrorCodes {
  const val TAG = "SherpaOnnxSeparation"

  const val DETECT_ERROR = "SEPARATION_DETECT_ERROR"

  const val SEPARATION_INIT_ERROR = "SEPARATION_INIT_ERROR"
  const val SEPARATION_ERROR = "SEPARATION_ERROR"
  const val SEPARATION_BUFFER_KIND_MISMATCH = "SEPARATION_BUFFER_KIND_MISMATCH"
  const val SEPARATION_BUFFER_NOT_FOUND = "SEPARATION_BUFFER_NOT_FOUND"
  const val SEPARATION_BUFFER_EMPTY = "SEPARATION_BUFFER_EMPTY"
  const val SEPARATION_OUTPUT_NOT_EMPTY = "SEPARATION_OUTPUT_NOT_EMPTY"
  const val SEPARATION_STEM_COUNT_MISMATCH = "SEPARATION_STEM_COUNT_MISMATCH"
  const val OFFLINE_OOM = "OFFLINE_OOM"
}
