package com.sherpaonnx.vad.core

object VadErrorCodes {
  const val BUFFER_NOT_FOUND = "VAD_BUFFER_NOT_FOUND"
  const val BUFFER_KIND_MISMATCH = "VAD_BUFFER_KIND_MISMATCH"
  const val INVALID_ARGUMENT = "VAD_INVALID_ARGUMENT"
  const val INVALID_STATE = "VAD_INVALID_STATE"
  const val MODEL_INIT_FAILED = "VAD_MODEL_INIT_FAILED"
  const val PIPELINE_NOT_FOUND = "VAD_PIPELINE_NOT_FOUND"
  const val PIPELINE_ALREADY_RUNNING = "VAD_PIPELINE_ALREADY_RUNNING"
  const val INTERNAL_ERROR = "VAD_INTERNAL_ERROR"
}
