import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingBottom: 100,
  },
  modeSelector: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  modeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 6,
    marginHorizontal: 4,
  },
  modeButtonActive: {
    backgroundColor: '#E3F2FD',
  },
  modeIcon: {
    marginRight: 6,
  },
  modeButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
  },
  modeButtonTextActive: {
    color: '#007AFF',
  },
  errorBox: {
    flexDirection: 'row',
    backgroundColor: '#FFEBEE',
    borderLeftColor: '#D32F2F',
    borderLeftWidth: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 4,
    marginBottom: 16,
    alignItems: 'center',
  },
  errorText: {
    color: '#D32F2F',
    fontSize: 13,
    marginLeft: 8,
    flex: 1,
  },
  modeContent: {
    gap: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
    marginBottom: 8,
  },
  sectionDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
    marginBottom: 10,
  },
  textInput: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#222',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    minHeight: 120,
    textAlignVertical: 'top',
  },
  optionList: {
    gap: 10,
  },
  optionCard: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  optionCardActive: {
    borderColor: '#007AFF',
    backgroundColor: '#E3F2FD',
  },
  optionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222',
    marginBottom: 4,
  },
  optionTitleActive: {
    color: '#007AFF',
  },
  optionDescription: {
    fontSize: 12,
    color: '#666',
    lineHeight: 17,
  },
  policyControl: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  policyLabel: {
    flex: 1,
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
  },
  policyInput: {
    width: 80,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#DDD',
    fontSize: 13,
    color: '#222',
    backgroundColor: '#FAFAFA',
  },
  button: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  secondaryButton: {
    backgroundColor: '#1F7AE0',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonIcon: {
    marginRight: 8,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '600',
  },
  fileSelectedBox: {
    backgroundColor: '#E3F2FD',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#90CAF9',
  },
  fileInfo: {
    flex: 1,
  },
  fileName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1976D2',
    marginBottom: 2,
  },
  fileUri: {
    fontSize: 12,
    color: '#666',
  },
  filePickerButton: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#007AFF',
    borderStyle: 'dashed',
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filePickerIcon: {
    marginBottom: 8,
  },
  filePickerText: {
    color: '#007AFF',
    fontSize: 14,
    fontWeight: '600',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 13,
    color: '#666',
  },
  warningContainer: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FFD54F',
    backgroundColor: '#FFF8E1',
    padding: 12,
  },
  warningText: {
    fontSize: 13,
    color: '#795548',
    lineHeight: 18,
  },
  infoCard: {
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BBDEFB',
    backgroundColor: '#EAF4FF',
    padding: 12,
  },
  infoText: {
    fontSize: 13,
    color: '#245A8D',
    lineHeight: 18,
  },
  modelButtons: {
    gap: 10,
  },
  modelSelectButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1D1D6',
    backgroundColor: '#F9F9FB',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  modelSelectButtonActive: {
    borderColor: '#007AFF',
    backgroundColor: '#E3F2FD',
  },
  modelSelectButtonInitialized: {
    borderColor: '#34C759',
  },
  modelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
  },
  modelSelectButtonTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1C1C1E',
  },
  modelSelectButtonTitleActive: {
    color: '#007AFF',
  },
  modelSelectButtonId: {
    fontSize: 12,
    color: '#6D6D72',
  },
  recommendedBadge: {
    borderRadius: 999,
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  recommendedBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#2E7D32',
    textTransform: 'uppercase',
  },
  statusCard: {
    marginTop: 12,
    borderRadius: 8,
    backgroundColor: '#E8F5E9',
    padding: 12,
  },
  statusTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1B5E20',
    marginBottom: 4,
  },
  statusText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#1B5E20',
  },
  timelineContainer: {
    marginBottom: 12,
  },
  timeline: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    height: 40,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    overflow: 'hidden',
  },
  timelineSegment: {
    height: '100%',
    borderRightWidth: 1,
    borderRightColor: '#FFF',
  },
  segmentCard: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  segmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  segmentIndex: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666',
    marginRight: 8,
    minWidth: 30,
  },
  reasonBadge: {
    backgroundColor: '#E0F2F1',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    marginRight: 8,
  },
  reasonBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#00897B',
  },
  segmentMeta: {
    fontSize: 11,
    color: '#999',
    marginLeft: 'auto',
  },
  segmentText: {
    fontSize: 13,
    color: '#333',
    lineHeight: 18,
  },
  segmentDetail: {
    fontSize: 11,
    color: '#666',
    marginTop: 4,
    fontStyle: 'italic',
  },
});
