package com.sherpaonnx.enhancement.core

internal object EnhancementErrorCodes {
  const val TAG = "SherpaOnnxEnhancement"

  const val DETECT_ERROR = "DETECT_ERROR"

  const val ENHANCEMENT_INIT_ERROR = "ENHANCEMENT_INIT_ERROR"
  const val ENHANCEMENT_ERROR = "ENHANCEMENT_ERROR"
  const val ENHANCEMENT_BUFFER_KIND_MISMATCH = "ENHANCEMENT_BUFFER_KIND_MISMATCH"
  const val ENHANCEMENT_BUFFER_NOT_FOUND = "ENHANCEMENT_BUFFER_NOT_FOUND"
  const val ENHANCEMENT_BUFFER_EMPTY = "ENHANCEMENT_BUFFER_EMPTY"
  const val ENHANCEMENT_OUTPUT_NOT_EMPTY = "ENHANCEMENT_OUTPUT_NOT_EMPTY"

  const val ONLINE_ENHANCEMENT_INIT_ERROR = "ONLINE_ENHANCEMENT_INIT_ERROR"
  const val ONLINE_ENHANCEMENT_ERROR = "ONLINE_ENHANCEMENT_ERROR"

  const val ENHANCEMENT_PIPELINE_BUFFER_NOT_FOUND = "ENHANCEMENT_PIPELINE_BUFFER_NOT_FOUND"
  const val ENHANCEMENT_PIPELINE_BUFFER_KIND_MISMATCH = "ENHANCEMENT_PIPELINE_BUFFER_KIND_MISMATCH"
  const val ENHANCEMENT_PIPELINE_BUFFER_NOT_RECORDING = "ENHANCEMENT_PIPELINE_BUFFER_NOT_RECORDING"
  const val ENHANCEMENT_PIPELINE_SAMPLE_RATE_MISMATCH = "ENHANCEMENT_PIPELINE_SAMPLE_RATE_MISMATCH"

  const val STREAMING_PIPELINE_ERROR = "STREAMING_PIPELINE_ERROR"
}