name: Setup Android NDK
description: Install Android NDK and export ANDROID_NDK_HOME/ANDROID_NDK_ROOT and an output `ndk-path` for workflows

inputs:
  ndk-version:
    description: 'NDK version to install (example: r29)'
    required: false
    default: 'r29'
  add-to-path:
    description: 'Whether to add the NDK bin to PATH'
    required: false
    default: 'true'

outputs:
  ndk-path:
    description: 'Path to the installed NDK'

runs:
  using: composite
  steps:
    - name: Install NDK
      id: install
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ inputs.ndk-version }}
        add-to-path: ${{ inputs.add-to-path }}

    - name: Export NDK environment and set output
      shell: bash
      run: |
        if [ -n "${{ steps.install.outputs.ndk-path }}" ]; then
          echo "ANDROID_NDK_HOME=${{ steps.install.outputs.ndk-path }}" >> "$GITHUB_ENV"
          echo "ANDROID_NDK_ROOT=${{ steps.install.outputs.ndk-path }}" >> "$GITHUB_ENV"
          # Prepend toolchain bin directory to PATH for immediate availability
          echo "PATH=${{ steps.install.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}" >> "$GITHUB_ENV"
          echo "ndk-path=${{ steps.install.outputs.ndk-path }}" >> "$GITHUB_OUTPUT"
          echo "[OK] Exported NDK path: ${{ steps.install.outputs.ndk-path }}"
        else
          echo "::warning::setup-ndk did not return ndk-path output"
          echo "ndk-path=" >> "$GITHUB_OUTPUT"
        fi
