import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F2F2F7',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 40,
    gap: 14,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    gap: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  sectionHint: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
  subsectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  inputDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputDividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#D1D5DB',
  },
  inputDividerText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    textTransform: 'uppercase',
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pickButtonOutline: {
    alignSelf: 'flex-start',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#007AFF',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  pickButtonOutlineText: {
    color: '#007AFF',
    fontSize: 14,
    fontWeight: '600',
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F9FAFB',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipActive: {
    borderColor: '#007AFF',
    backgroundColor: '#DBEAFE',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
  },
  sourceLabel: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '600',
  },
  sourceMeta: {
    fontSize: 12,
    color: '#6B7280',
  },
  inlineInfoText: {
    fontSize: 13,
    color: '#6B7280',
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  loadingText: {
    fontSize: 14,
    color: '#374151',
  },
  errorText: {
    fontSize: 14,
    color: '#B91C1C',
    lineHeight: 20,
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 8,
    columnGap: 8,
  },
  metaItem: {
    minWidth: '47%',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  metaLabel: {
    fontSize: 11,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    fontWeight: '700',
  },
  metaValue: {
    marginTop: 2,
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  segmented: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#EEF2F7',
    borderRadius: 10,
    padding: 3,
    gap: 4,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: 'center',
  },
  segmentButtonActive: {
    backgroundColor: '#007AFF',
  },
  segmentButtonDisabled: {
    opacity: 0.4,
  },
  segmentText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  timelineControls: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    gap: 10,
  },
  timelineSummary: {
    fontSize: 13,
    color: '#4B5563',
    fontWeight: '600',
  },
  transportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  transportButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  transportButton: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  transportButtonDisabled: {
    opacity: 0.35,
  },
  transportButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
  },
  progressTrack: {
    height: 22,
    justifyContent: 'center',
  },
  progressRail: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#D1D5DB',
    overflow: 'hidden',
  },
  progressFill: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#007AFF',
  },
  progressThumb: {
    position: 'absolute',
    top: -5,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#007AFF',
    marginLeft: -9,
  },
  disabledNote: {
    fontSize: 13,
    color: '#92400E',
    backgroundColor: '#FFFBEB',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FDE68A',
    padding: 10,
  },
  chartNote: {
    fontSize: 12,
    lineHeight: 18,
    color: '#4B5563',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  insightGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  insightCard: {
    minWidth: '47%',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  insightLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    fontWeight: '700',
    color: '#64748B',
  },
  insightValue: {
    marginTop: 3,
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  placeholderSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 18,
    alignItems: 'center',
  },
  placeholderText: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
  },
});
