package com.sherpaonnx.stt.core

/**
 * Unified STT error codes. Must match iOS and TypeScript.
 */
object SttErrorCodes {
  const val INVALID_ARGUMENT = "STT_INVALID_ARGUMENT"
  const val INSTANCE_NOT_FOUND = "STT_INSTANCE_NOT_FOUND"
  const val NOT_INITIALIZED = "STT_NOT_INITIALIZED"
  const val INIT_FAILED = "STT_INIT_FAILED"
  const val MODEL_DETECTION_FAILED = "STT_MODEL_DETECTION_FAILED"
  const val MODEL_UNSUPPORTED_HARDWARE = "STT_MODEL_UNSUPPORTED_HARDWARE"
  const val CONFIG_FAILED = "STT_CONFIG_FAILED"
  const val TRANSCRIBE_FAILED = "STT_TRANSCRIBE_FAILED"
  const val BUFFER_NOT_FOUND = "STT_BUFFER_NOT_FOUND"
  const val BUFFER_KIND_MISMATCH = "STT_BUFFER_KIND_MISMATCH"
  const val BUFFER_EMPTY = "STT_BUFFER_EMPTY"
  const val RESULT_EMPTY = "STT_RESULT_EMPTY"
  const val RESULT_NOT_FOUND = "STT_RESULT_NOT_FOUND"
  const val STALE_RESULT = "STT_STALE_RESULT"
  const val SLICE_INVALID = "STT_SLICE_INVALID"
  const val SLICE_TOO_LARGE = "STT_SLICE_TOO_LARGE"
  const val STREAM_INSTANCE_NOT_FOUND = "STT_STREAM_INSTANCE_NOT_FOUND"
  const val STREAM_NOT_FOUND = "STT_STREAM_NOT_FOUND"
  const val STREAM_DECODE_FAILED = "STT_STREAM_DECODE_FAILED"
  const val STREAM_FINAL_NOT_AVAILABLE = "STT_STREAM_FINAL_NOT_AVAILABLE"
  const val OFFLINE_OOM = "OFFLINE_OOM"
  const val INTERNAL_ERROR = "STT_INTERNAL_ERROR"

  const val STT_DEFAULT_SLICE_COUNT = 1024
  const val STT_MAX_SLICE_COUNT = 16384
}
